// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AllWord struct {
	ID   int64  `json:"id"`
	Word string `json:"word"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Created      pgtype.Timestamptz `json:"created"`
	Interact     pgtype.Timestamptz `json:"interact"`
	Coins        int64              `json:"coins"`
}

type UserAttempt struct {
	ID       int32  `json:"id"`
	UserID   int64  `json:"user_id"`
	WordID   int64  `json:"word_id"`
	UserWord string `json:"user_word"`
}

type UserGift struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Link        pgtype.UUID `json:"link"`
}

type Words5 struct {
	WordID   int64            `json:"word_id"`
	WordDate pgtype.Timestamp `json:"word_date"`
}
